variables:
  DEBIAN_FRONTEND: noninteractive
  MYSQL_DATABASE: data
  MYSQL_ROOT_PASSWORD: password
  MYSQL_HOST: mysql

default:
  image: ubuntu:20.04
  before_script:
    - apt-get -y update
    - apt-get -y install python3.10 python3-pip mysql-client libmysqlclient-dev pkg-config
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt


django-tests:
  stage: test
  services:
    - mysql
  script:
    - echo "SHOW tables;" | mysql -u root -p"$MYSQL_ROOT_PASSWORD" -h "${MYSQL_HOST}" "${MYSQL_DATABASE}"
    - python3 manage.py test

