# Generated by Django 4.2.4 on 2023-08-09 21:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('text', models.TextField(verbose_name='news text')),
                ('tags', django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=2500, size=None)),
                ('source', models.URLField(verbose_name='source of news url')),
            ],
        ),
    ]
